# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Installation
    init: sudo add-apt-repository ppa:ondrej/php && sudo apt install php8.1 php8.1-dom php8.1-mbstring php8.1-xml php8.1-xmlwriter
